dist: trusty
language: csharp
solution: PagarMe.sln
install:
 - sudo apt-get install -y nunit-console gtk-sharp2
 - nuget restore PagarMe.sln
script:
 - xbuild PagarMe.sln
 - nunit-console ./PagarMe.Tests/bin/Debug/PagarMe.Tests.dll

